/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab9p2_kevinwilmer;

import Clases.Idioma;
import Clases.Juego;
import Clases.cuentas;
import DataBase.Dba;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lab9.LibLab9;

/**
 *
 * @author Usuario
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    private LibLab9 lib = new LibLab9();
    

    public void enviarCorreo() {
        lib.sendMail(jTextArea1.getText(), jTextField3.getText(), jTextField2.getText());
    }

    public Principal() {
        initComponents();
        TraerIdiom();
        traerJuegos();
        actualizarcb();
        actualizarTablaTodos();
        actualizarTablaIdiomas();
        lib.setProgressBar(jProgressBar1);
        lib.colorRand(true);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        button_generar = new javax.swing.JToggleButton();
        button_ejecutar = new javax.swing.JToggleButton();
        cb_query = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nombreNew = new javax.swing.JTextField();
        nombreOld = new javax.swing.JTextField();
        categoriaOld = new javax.swing.JTextField();
        costoOld = new javax.swing.JTextField();
        costoNew = new javax.swing.JTextField();
        categoriaNew = new javax.swing.JTextField();
        jProgressBar1 = new javax.swing.JProgressBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JToggleButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        button_generar.setText("Generar");
        button_generar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_generarActionPerformed(evt);
            }
        });
        jPanel1.add(button_generar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 140, -1));

        button_ejecutar.setText("Ejecutar");
        button_ejecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_ejecutarActionPerformed(evt);
            }
        });
        jPanel1.add(button_ejecutar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 140, -1));

        cb_query.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Crear", "Modificar", "Eliminar", "Seleccionar" }));
        jPanel1.add(cb_query, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 140, -1));

        jLabel1.setText("Nombre");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 70, 20));

        jLabel2.setText("Costo");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 60, 20));

        jLabel3.setText("Categoria");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 70, 20));
        jPanel1.add(nombreNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, 110, -1));
        jPanel1.add(nombreOld, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 110, -1));
        jPanel1.add(categoriaOld, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, 110, -1));
        jPanel1.add(costoOld, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 110, -1));
        jPanel1.add(costoNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, 110, -1));
        jPanel1.add(categoriaNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, 110, -1));
        jPanel1.add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 500, 40));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Categoría", "Costo", "Idiomas"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 500, 160));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Categoría", "Costo", "Idioma"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setResizable(false);
            jTable2.getColumnModel().getColumn(1).setResizable(false);
            jTable2.getColumnModel().getColumn(2).setResizable(false);
            jTable2.getColumnModel().getColumn(3).setResizable(false);
            jTable2.getColumnModel().getColumn(4).setResizable(false);
        }

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 500, 160));

        jTabbedPane1.addTab("Juego", jPanel1);

        jPanel2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanel2FocusGained(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel4.setText("Nombre");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 100, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel5.setText("Idioma a Juego");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 120, -1));

        jPanel2.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, 220, 30));
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 230, 30));

        jButton1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButton1.setText("Agregar");
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 230, 40));

        jButton2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButton2.setText("Crear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 230, 40));

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable3);
        if (jTable3.getColumnModel().getColumnCount() > 0) {
            jTable3.getColumnModel().getColumn(0).setResizable(false);
            jTable3.getColumnModel().getColumn(1).setResizable(false);
        }

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 490, 370));

        jTabbedPane1.addTab("Idioma", jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setText("Para");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        jLabel7.setText("Asunto");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jLabel8.setText("Mensaje");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jPanel3.add(jTextArea1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 520, 360));
        jPanel3.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 290, 30));
        jPanel3.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 290, 30));

        jToggleButton1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jToggleButton1.setText("Enviar");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 50, -1, -1));

        jTabbedPane1.addTab("Correo", jPanel3);

        jMenu1.setText("Archivos");

        jMenuItem1.setText("Abrir Archivos");
        jMenu1.add(jMenuItem1);

        jMenu2.setText("Archivos Recientes");
        jMenu1.add(jMenu2);

        jMenuItem2.setText("Limpiar");
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Salir");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 612, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        enviarCorreo();
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void button_ejecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_ejecutarActionPerformed
//hace alguna kkk del crud

        Dba bd = new Dba("../BaseDatosLab9P2_KevinWilmer.accdb");
        if ((cb_query.getSelectedItem().toString()).equals("Crear")) {
            //Dba bd = new Dba("../BaseDatosLab9P2_KevinWilmer.accdb");
            bd.conectar();
            try {
                bd.query.execute("insert into Juego (Categoria, Costo, Nombre)"
                        + "VALUES ('" + categoriaOld.getText() + "', '" + Integer.parseInt(costoOld.getText()) + "', '" + nombreOld.getText() + "')");
                bd.commit();

                JOptionPane.showMessageDialog(this, "Juego Registrado", "Exito", JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception e) {
                e.printStackTrace();
            }
            bd.desconectar();
        } else if ((cb_query.getSelectedItem().toString()).equals("Modificar")) {
            bd.conectar();
            try {
                bd.query.execute("update Juego set Categoria='" + categoriaNew.getText() + "', Costo=" + Integer.parseInt(costoNew.getText()) + ", Nombre='" + nombreNew.getText() + "' where Nombre='" + nombreOld.getText() + "'");
                bd.commit();

                JOptionPane.showMessageDialog(this, "Juego Modificado", "Exito", JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception e) {
                e.printStackTrace();
            }
            bd.desconectar();
        } else if ((cb_query.getSelectedItem().toString()).equals("Eliminar")) {
            bd.conectar();
            try {
                bd.query.execute("delete from Juego where Nombre='" + nombreOld.getText() + "'");
                //+ "VALUES ('" + categoriaOld.getText() + "', '" + Integer.parseInt(costoOld.getText()) + "', '" + nombreOld.getText() + "')");
                bd.commit();

                JOptionPane.showMessageDialog(this, "Juego Eliminado", "Exito", JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception e) {
                e.printStackTrace();
            }
            bd.desconectar();
        } else if ((cb_query.getSelectedItem().toString()).equals("Seleccionar")) {

        }
        traerJuegos();
        actualizarcb();
        actualizarTablaTodos();
    }//GEN-LAST:event_button_ejecutarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Dba bd = new Dba("../BaseDatosLab9P2_KevinWilmer.accdb");
        bd.conectar();
        try {
            bd.query.execute("insert into Idiomas (NombreIdioma, ID_Juegos)"
                    + "VALUES ('" + jTextField1.getText() + "', " + ((Juego)jComboBox1.getSelectedItem()).getId()+ ")");
            bd.commit();

            JOptionPane.showMessageDialog(this, "Idioma Registrado", "Exito", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            e.printStackTrace();
        }
        bd.desconectar();
        TraerIdiom();
        actualizarTablaIdiomas();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jPanel2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel2FocusGained
        traerJuegos();
        actualizarcb();

    }//GEN-LAST:event_jPanel2FocusGained

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        actualizarTablaTodos();
    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void button_generarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_generarActionPerformed
        
        JFileChooser jfc = new JFileChooser();
        File archivo;
        int op = jfc.showSaveDialog(this);
        if (op == JFileChooser.APPROVE_OPTION) {
            archivo = jfc.getSelectedFile();
        }
    }//GEN-LAST:event_button_generarActionPerformed

    public void actualizarcb() {
        DefaultComboBoxModel modelo = (DefaultComboBoxModel) jComboBox1.getModel();
        modelo.removeAllElements();

        for (Juego juego : j) {
            modelo.addElement(juego);
        }
        jComboBox1.setModel(modelo);
    }

    public void traerJuegos() {
        Dba bd = new Dba("../BaseDatosLab9P2_KevinWilmer.accdb");
        bd.conectar();
        try {
            //String contraseña = lib.encrypt(contraLogin.getText());
            bd.query.execute("select * from Juego");
            ResultSet rs = bd.query.getResultSet();
            j = new ArrayList();
            while (rs.next()) {
                Juego temp = new Juego();
                temp.setId(rs.getInt("Id"));
                temp.setCategoria(rs.getString("Categoria"));
                temp.setCosto(rs.getInt("Costo"));
                temp.setNombre(rs.getString("Nombre"));

                j.add(temp);
            }
            bd.commit();

            //JOptionPane.showMessageDialog(this, "Usuario Registrado", "Exito", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            e.printStackTrace();
        }
        bd.desconectar();
        actualizarcb();
        actualizarTablaIdiomas();
    }
    
    public void TraerIdiom() {
        Dba bd = new Dba("../BaseDatosLab9P2_KevinWilmer.accdb");
        bd.conectar();
        try {
            //String contraseña = lib.encrypt(contraLogin.getText());
            bd.query.execute("select * from Idiomas");
            ResultSet rs = bd.query.getResultSet();
            idiom = new ArrayList();
            while (rs.next()) {
                Idioma temp = new Idioma();
                temp.setNombres(rs.getString("NombreIdioma"));
                temp.setId(rs.getInt("Id"));

                idiom.add(temp);
            }
            bd.commit();

            //JOptionPane.showMessageDialog(this, "Usuario Registrado", "Exito", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            e.printStackTrace();
        }
        bd.desconectar();

    }
    
    public void actualizarTablaTodos(){
        DefaultTableModel m = (DefaultTableModel)jTable2.getModel();
        m.setNumRows(0);
        for (Juego juego : j) {
            Object[] row = new Object[5]; 
            row[0] = juego.getId();
            row[1] = juego.getNombre();
            row[2] = juego.getCategoria();
            row[3] = juego.getCosto();
            row[4] = juego.getI();
            m.addRow(row);
        }
        
        jTable2.setModel(m);
    }
    
    public void actualizarTablaIdiomas(){
        DefaultTableModel m = (DefaultTableModel)jTable3.getModel();
        m.setNumRows(0);
        for (Idioma idioma : idiom) {
            Object[] row = new Object[2]; 
            row[0] = idioma.getId();
            row[1] = idioma.getNombres();
            m.addRow(row);
        }
        
        jTable3.setModel(m);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    private ArrayList<Idioma> idiom = new ArrayList();
    private ArrayList<String> query = new ArrayList();
    private ArrayList<Juego> j = new ArrayList();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton button_ejecutar;
    private javax.swing.JToggleButton button_generar;
    private javax.swing.JTextField categoriaNew;
    private javax.swing.JTextField categoriaOld;
    private javax.swing.JComboBox<String> cb_query;
    private javax.swing.JTextField costoNew;
    private javax.swing.JTextField costoOld;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextField nombreNew;
    private javax.swing.JTextField nombreOld;
    // End of variables declaration//GEN-END:variables
}
